package proyectoFinal;

import java.awt.HeadlessException;
import java.io.*;
import java.util.Random;
import javax.swing.*;

public class altasGimnasio extends javax.swing.JFrame {

    /**
     * Creates new form gimnasio
     */
    public altasGimnasio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Subtitulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        dir = new javax.swing.JTextField();
        Dirección = new javax.swing.JLabel();
        Deporte = new javax.swing.JLabel();
        deporte = new javax.swing.JComboBox<>();
        Peso = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        Edad = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        regresar = new javax.swing.JButton();
        capturar = new javax.swing.JButton();
        generar_Clave = new javax.swing.JButton();
        reporte = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Subtitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subtitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoFinal/altas.png"))); // NOI18N

        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nombre.setText("Nombre:");
        Nombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoFinal/Captura de pantalla 2023-07-26 203359.png"))); // NOI18N

        Clave.setForeground(new java.awt.Color(0, 0, 0));
        Clave.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Clave.setText("Clave:");
        Clave.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        clave.setEditable(false);

        Telefono.setForeground(new java.awt.Color(0, 0, 0));
        Telefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Telefono.setText("Telefono:");
        Telefono.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });

        dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirActionPerformed(evt);
            }
        });

        Dirección.setForeground(new java.awt.Color(0, 0, 0));
        Dirección.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Dirección.setText("Dirección:");
        Dirección.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Deporte.setForeground(new java.awt.Color(0, 0, 0));
        Deporte.setText("Deporte:");

        deporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CROSSFIT", "CICLISMO", "PILATES", "ZUMBA" }));
        deporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deporteActionPerformed(evt);
            }
        });

        Peso.setForeground(new java.awt.Color(0, 0, 0));
        Peso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Peso.setText("Peso:");
        Peso.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        Edad.setForeground(new java.awt.Color(0, 0, 0));
        Edad.setText("Edad:");

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        capturar.setText("Capturar");
        capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarActionPerformed(evt);
            }
        });

        generar_Clave.setText("Generar Clave");
        generar_Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_ClaveActionPerformed(evt);
            }
        });

        reporte.setText("Reporte");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        Reporte.setEditable(false);
        Reporte.setColumns(20);
        Reporte.setRows(5);
        jScrollPane2.setViewportView(Reporte);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(regresar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(Clave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clave, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(generar_Clave))
                                    .addComponent(nom)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Deporte)
                                    .addComponent(Peso)
                                    .addComponent(Edad)
                                    .addComponent(Telefono))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(tel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(peso)
                                            .addComponent(deporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(edad)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reporte)
                                .addGap(125, 125, 125)
                                .addComponent(capturar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dirección)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dir))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Subtitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(nom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Clave)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generar_Clave))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Telefono)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dirección))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deporte)
                            .addComponent(deporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Peso)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edad)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capturar)
                            .addComponent(regresar)
                            .addComponent(reporte))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        menuGimnasio menu = new menuGimnasio();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void capturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturarActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("C:\\Gimnasio\\archivo.txt", true);
            DataOutputStream salida = new DataOutputStream(fos);

            int clave = Integer.parseInt(this.clave.getText());
            salida.writeInt(clave);
            String nom = this.nom.getText();
            salida.writeUTF(nom);
            long tel = Long.parseLong(this.tel.getText());
            salida.writeLong(tel);
            String dir = this.dir.getText();
            salida.writeUTF(dir);
            String deporte = (String) this.deporte.getSelectedItem();
            salida.writeUTF(deporte);
            int peso = Integer.parseInt(this.peso.getText());
            salida.writeInt(peso);
            int edad = Integer.parseInt(this.edad.getText());
            salida.writeInt(edad);
            JOptionPane.showMessageDialog(null, "Datos registrados correctamente", "Aviso", 1);
        } catch (HeadlessException | IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_capturarActionPerformed

    private void generar_ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_ClaveActionPerformed
        // TODO add your handling code here:
                Random Rdm = new Random();
        clave.setText(String.valueOf(Rdm.nextInt(0, 1000)));
    }//GEN-LAST:event_generar_ClaveActionPerformed

    private void deporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deporteActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        try {
            StringBuilder reporteBuilder = new StringBuilder();
            FileInputStream fis = new FileInputStream(new File("C:\\Gimnasio\\archivo.txt"));
            DataInputStream entrada = new DataInputStream(fis);
            reporteBuilder.append("Clave ; Nombre ; Telefono ; Direccion ; Deporte ; Peso ; Edad\n");
            do {
                try {
                    reporteBuilder.append(entrada.readInt()).append(" ; ");
                    reporteBuilder.append(entrada.readUTF()).append(" ; ");
                    reporteBuilder.append(entrada.readLong()).append(" ; ");
                    reporteBuilder.append(entrada.readUTF()).append(" ; ");
                    reporteBuilder.append(entrada.readUTF()).append(" ; ");
                    reporteBuilder.append(entrada.readInt()).append(" ; ");
                    reporteBuilder.append(entrada.readInt()).append("\n");
                    reporteBuilder.append("-----------------------\n");
                    Reporte.setText(reporteBuilder.toString());
                } catch (EOFException e) {
                    JOptionPane.showMessageDialog(null, "Fin del Fichero");
                    break;
                }
            } while (true);
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altasGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new altasGimnasio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Deporte;
    private javax.swing.JLabel Dirección;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Peso;
    private javax.swing.JTextArea Reporte;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton capturar;
    private javax.swing.JTextField clave;
    private javax.swing.JComboBox<String> deporte;
    private javax.swing.JTextField dir;
    private javax.swing.JTextField edad;
    private javax.swing.JButton generar_Clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField peso;
    private javax.swing.JButton regresar;
    private javax.swing.JButton reporte;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
