package proyectoFinal;

import java.awt.HeadlessException;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author rocv0
 */
public class diarioGimnasio extends javax.swing.JFrame {

    /**
     * Creates new form diarioGimnasio
     */
    public diarioGimnasio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulos = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        Hora = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();
        horaSel = new javax.swing.JComboBox<>();
        regresar = new javax.swing.JButton();
        capturar = new javax.swing.JButton();
        JScrollPane1 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();
        reporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        Titulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoFinal/diario.png"))); // NOI18N

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoFinal/diario2.jpg"))); // NOI18N

        Clave.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Clave.setText("Clave:");

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        Nombre.setText("Nombre:");

        nom.setEditable(false);

        Hora.setText("Hora:");

        horaSel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        horaSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaSelActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        capturar.setText("Capturar");
        capturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturarActionPerformed(evt);
            }
        });

        Reporte.setEditable(false);
        Reporte.setColumns(20);
        Reporte.setRows(5);
        JScrollPane1.setViewportView(Reporte);

        reporte.setText("Reporte");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Icono)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Clave)
                            .addComponent(Nombre)
                            .addComponent(Hora))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(regresar)
                                .addGap(32, 32, 32)
                                .addComponent(capturar)
                                .addGap(125, 125, 125))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(clave)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nom)
                                            .addComponent(hora))
                                        .addGap(18, 18, 18)
                                        .addComponent(horaSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(reporte)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulos)
                    .addComponent(JScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Icono))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Clave)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hora)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(horaSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capturar)
                            .addComponent(regresar))
                        .addGap(18, 18, 18)
                        .addComponent(reporte)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        menuGimnasio menu = new menuGimnasio();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void capturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturarActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fos = new FileOutputStream("C:\\Gimnasio\\diario.txt", true);
            DataOutputStream salida = new DataOutputStream(fos);

            int clave = Integer.parseInt(this.clave.getText());
            salida.writeInt(clave);
            String nom = this.nom.getText();
            salida.writeUTF(nom);
            
            
            String horaSel = (String) this.horaSel.getSelectedItem();
            if (horaSel.equalsIgnoreCase("Entrada")) {
                String ent = "Ent: " + this.hora.getText();
                salida.writeUTF(ent);
                JOptionPane.showMessageDialog(null, "Entrada registrada correctamente", "Aviso", 1);
            } else {
                String sal = "Sal: " + this.hora.getText();
                salida.writeUTF(sal);
                JOptionPane.showMessageDialog(null, "Salida registrada correctamente", "Aviso", 1);
            }
            
            
        } catch (HeadlessException | IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_capturarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        int clave = Integer.parseInt(this.clave.getText());

        try {
            FileInputStream fis = new FileInputStream(new File("C:\\Gimnasio\\archivo.txt"));
            DataInputStream entrada = new DataInputStream(fis);
            do {
                try {
                    int c2 = entrada.readInt();
                    if (c2 == clave) {
                        nom.setText(entrada.readUTF());
                        break;
                    }
                } catch (EOFException e) {
                    JOptionPane.showMessageDialog(null, "No se ha encontrado la clave", "Error", 0);
                    break;
                }
            } while (true);
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void horaSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaSelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaSelActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        // TODO add your handling code here:
        try {
            StringBuilder reporteBuilder = new StringBuilder();
            FileInputStream fis = new FileInputStream(new File("C:\\Gimnasio\\diario.txt"));
            DataInputStream entrada = new DataInputStream(fis);
            reporteBuilder.append("Clave ; Nombre ; Hora\n");
            do {
                try {
                    reporteBuilder.append(entrada.readInt()).append(" ; ");
                    reporteBuilder.append(entrada.readUTF()).append(" ; ");
                    reporteBuilder.append(entrada.readUTF()).append(" ; \n");
                    reporteBuilder.append("-----------------------\n");
                    Reporte.setText(reporteBuilder.toString());
                } catch (EOFException e) {
                    JOptionPane.showMessageDialog(null, "Fin del Fichero");
                    break;
                }
            } while (true);
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diarioGimnasio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new diarioGimnasio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Icono;
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextArea Reporte;
    private javax.swing.JLabel Titulos;
    private javax.swing.JButton buscar;
    private javax.swing.JButton capturar;
    private javax.swing.JTextField clave;
    private javax.swing.JTextField hora;
    private javax.swing.JComboBox<String> horaSel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom;
    private javax.swing.JButton regresar;
    private javax.swing.JButton reporte;
    // End of variables declaration//GEN-END:variables
}
